theme:
  active: Blue # current playing song in list
  banner: Green # the "spotify-tui" banner on launch
  error_border: Red # error dialog border
  error_text: Red # error message text (e.g. "Spotify API reported error 404")
  hint: Yellow # hint text in errors
  hovered: "94, 129, 172 " # hovered pane border
  inactive: "97, 110, 136" # borders of inactive panes
  playbar_background: "59, 66, 82" # background of progress bar
  playbar_progress: Blue # filled-in part of the progress bar
  playbar_progress_text: "48, 52, 64" # song length and time played/left indicator in the progress bar
  playbar_text: White # artist name in player pane
  selected: Blue # a) selected pane border, b) hovered item in list, & c) track title in player
  text: White # text in panes
  header: Magenta # header text in panes (e.g. 'Title', 'Artist', etc.)

behavior:
  seek_milliseconds: 5000
  volume_increment: 10
  # The lower the number the higher the "frames per second". You can decrease this number so that the audio visualisation is smoother but this can be expensive!
  tick_rate_milliseconds: 100
  # Enable text emphasis (typically italic/bold text styling). Disabling this might be important if the terminal config is otherwise restricted and rendering text escapes interferes with the UI.
  enable_text_emphasis: true
  # Controls whether to show a loading indicator in the top right of the UI whenever communicating with Spotify API
  show_loading_indicator: true
  # Disables the responsive layout that makes the search bar smaller on bigger
  # screens and enforces a wide search bar
  enforce_wide_search_bar: false
  # Determines the text icon to display next to "liked" Spotify items, such as
  # liked songs and albums, or followed artists. Can be any length string.
  # These icons require a patched nerd font.
  liked_icon: ‚ô•
  shuffle_icon: üîÄ
  repeat_track_icon: üîÇ
  repeat_context_icon: üîÅ
  playing_icon: ‚ñ∂
  paused_icon: ‚è∏
  set_window_title: true

keybindings:
  back: "q"
  jump_to_album: "a"
  jump_to_artist_album: "A"
  manage_devices: "d"
  decrease_volume: "ctrl-d"
  increase_volume: "ctrl-u"
  toggle_playback: " "
  seek_backwards: "ctrl-p"
  seek_forwards: "ctrl-n"
  next_track: "n"
  previous_track: "p"
  copy_song_url: "y"
  copy_album_url: "Y"
  help: "?"
  shuffle: "s"
  repeat: "r"
  search: "/"
  audio_analysis: "v"
  jump_to_context: "o"
  basic_view: "B"
  add_item_to_queue: "z"
